# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  at_odds_config = debug

else ifeq ($(config),release)
  at_odds_config = release

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := at_odds

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

at_odds:
ifneq (,$(at_odds_config))
	@echo "==== Building at_odds ($(at_odds_config)) ===="
	@${MAKE} --no-print-directory -C . -f at_odds.make config=$(at_odds_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f at_odds.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   at_odds"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"